### ISSUE TITLE
Error: cb is not a function

### ISSUE THREAD

**Issue by rfink** [getconversio/node-bigcommerce#36]
In generic request errors (such as timeout), the library fails if used with promises, as the callback function is not supplied:

Error: Error: socket hang up
/Users/rfink/code/node-bigcommerce/lib/request.js:156
    return cb(e);
           ^

TypeError: cb is not a function
    at ClientRequest.<anonymous> (/Users/rfink/code/node-bigcommerce/lib/request.js:156:12)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketCloseListener (_http_client.js:377:9)
    at emitOne (events.js:120:20)
    at TLSSocket.emit (events.js:210:7)
    at _handle.close (net.js:549:12)
    at TCP.done [as _onclose] (_tls_wrap.js:350:7)

Pull request incoming

**Comment by dlebech** [comment]
Thanks again @rfink, the fix from #37 has been published in version 2.5.2 :beers:

**Comment by rfink** [comment]
Thanks!
